# Generated by Django 4.2.7 on 2025-08-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
